// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/rwpp/RzWeLook/sms/grpc"
	"github.com/rwpp/RzWeLook/sms/ioc"
	"github.com/rwpp/RzWeLook/wego"
)

// Injectors from wire.go:

func Init() *wego.App {
	service := ioc.InitSmsTencentService()
	smsServiceServer := grpc.NewSmsServiceServer(service)
	client := ioc.InitEtcdClient()
	loggerV1 := ioc.InitLogger()
	server := ioc.InitGRPCxServer(smsServiceServer, client, loggerV1)
	app := &wego.App{
		GRPCServer: server,
	}
	return app
}
