services:
  postgres:
    image: postgres:17
    container_name: rzw-flow-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./script/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "15432:5432"