global:
  external_labels:
    monitor: 'prometheus-monitor'

scrape_configs:
  - job_name: "RzWelook"
    scrape_interval: 5s
    scrape_timeout: 3s
    static_configs:
      - targets: [ "host.docker.bff:8081"]