// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rwpp/RzWeLook/interactive/events"
	repository2 "github.com/rwpp/RzWeLook/interactive/repository"
	cache2 "github.com/rwpp/RzWeLook/interactive/repository/cache"
	dao2 "github.com/rwpp/RzWeLook/interactive/repository/dao"
	service2 "github.com/rwpp/RzWeLook/interactive/service"
	"github.com/rwpp/RzWeLook/internal/events/article"
	"github.com/rwpp/RzWeLook/internal/ioc"
	"github.com/rwpp/RzWeLook/internal/repository"
	"github.com/rwpp/RzWeLook/internal/repository/cache"
	"github.com/rwpp/RzWeLook/internal/repository/dao"
	"github.com/rwpp/RzWeLook/internal/service"
	"github.com/rwpp/RzWeLook/internal/web"
	"github.com/rwpp/RzWeLook/internal/web/jwt"
)

// Injectors from wire.go:

func InitApp() *App {
	cmdable := ioc.InitRedis()
	handler := jwt.NewRedisJWTHandler(cmdable)
	v := ioc.InitMiddleware(cmdable, handler)
	db := ioc.InitDB()
	userDAO := dao.NewUserDAO(db)
	userCacheInterface := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCacheInterface)
	userService := service.NewUserService(userRepository)
	codeCacheInterface := cache.NewCodeCache(cmdable)
	codeRepositoryInterface := repository.NewCodeRepository(codeCacheInterface)
	smsService := ioc.InitSMSService()
	codeServiceInterface := service.NewCodeService(codeRepositoryInterface, smsService)
	loggerV1 := ioc.InitLogger()
	userHandler := web.NewUserHandler(userService, codeServiceInterface, handler, loggerV1)
	wechatService := ioc.InitOAuthWechatService()
	wechatHandlerConfig := ioc.NewWechatHandler()
	oAuthWechatHandler := web.NewOAuthWechatHandler(wechatService, userService, handler, wechatHandlerConfig)
	articleDAO := dao.NewGORMArticleDAO(db)
	articleCache := cache.NewRedisArticleCache(cmdable)
	articleRepository := repository.NewArticleRepository(articleDAO, articleCache, loggerV1, userRepository)
	client := ioc.InitKafka()
	syncProducer := ioc.NewSyncProducer(client)
	producer := article.NewKafkaProducer(syncProducer)
	articleService := service.NewArticleService(articleRepository, loggerV1, producer)
	interactiveDAO := dao2.NewGORMInteractiveDAO(db)
	interactiveCache := cache2.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository2.NewCachedInteractiveRepository(interactiveDAO, interactiveCache, loggerV1)
	interactiveService := service2.NewInteractiveService(interactiveRepository, loggerV1)
	interactiveServiceClient := ioc.InitIntrGRPCClient(interactiveService)
	articleHandler := web.NewArticleHandler(articleService, interactiveServiceClient, loggerV1)
	engine := ioc.InitWeb(v, userHandler, oAuthWechatHandler, articleHandler)
	interactiveReadEventConsumer := events.NewInteractiveReadEventConsumer(client, interactiveRepository, loggerV1)
	v2 := ioc.NewConsumers(interactiveReadEventConsumer)
	rankingCache := cache.NewRankingCache(cmdable)
	rankingLocalCache := cache.NewRankingLocalCache()
	rankingRepository := repository.NewRankingRepository(rankingCache, rankingLocalCache)
	rankingService := service.NewRankingService(articleService, interactiveServiceClient, rankingRepository)
	rlockClient := ioc.InitRLockClient(cmdable)
	rankingJob := ioc.InitRankingJob(rankingService, rlockClient, loggerV1)
	cron := ioc.InitJobs(loggerV1, rankingJob)
	app := &App{
		web:       engine,
		consumers: v2,
		cron:      cron,
	}
	return app
}

// wire.go:

var interactiveSvcProvider = wire.NewSet(service2.NewInteractiveService, repository2.NewCachedInteractiveRepository, dao2.NewGORMInteractiveDAO, cache2.NewRedisInteractiveCache)

var rankingServiceSet = wire.NewSet(cache.NewRankingCache, cache.NewRankingLocalCache, repository.NewRankingRepository, service.NewRankingService)
