// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rwpp/RzWeLook/oauth2/grpc"
	"github.com/rwpp/RzWeLook/oauth2/ioc"
)

// Injectors from wire.go:

func Init() *App {
	loggerV1 := ioc.InitLogger()
	service := ioc.InitPrometheus(loggerV1)
	oauth2ServiceServer := grpc.NewOauth2ServiceServer(service)
	server := ioc.InitGRPCxServer(oauth2ServiceServer)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitLogger)
