// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rwpp/RzWeLook/code/grpc"
	"github.com/rwpp/RzWeLook/code/ioc"
	"github.com/rwpp/RzWeLook/code/repository"
	"github.com/rwpp/RzWeLook/code/repository/cache"
	"github.com/rwpp/RzWeLook/code/service"
)

// Injectors from wire.go:

func Init() *App {
	cmdable := ioc.InitRedis()
	codeCacheInterface := cache.NewCodeCache(cmdable)
	codeRepositoryInterface := repository.NewCodeRepository(codeCacheInterface)
	smsServiceClient := ioc.InitSmsRpcClient()
	codeServiceInterface := service.NewCodeService(codeRepositoryInterface, smsServiceClient)
	codeServiceServer := grpc.NewCodeServiceServer(codeServiceInterface)
	client := ioc.InitEtcdClient()
	loggerV1 := ioc.InitLogger()
	server := ioc.InitGRPCxServer(codeServiceServer, client, loggerV1)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitRedis, ioc.InitEtcdClient, ioc.InitLogger)
