// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rwpp/RzWeLook/cronjob/grpc"
	"github.com/rwpp/RzWeLook/cronjob/ioc"
	"github.com/rwpp/RzWeLook/cronjob/repository"
	"github.com/rwpp/RzWeLook/cronjob/repository/dao"
	"github.com/rwpp/RzWeLook/cronjob/service"
)

// Injectors from wire.go:

func Init() *App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	jobDAO := dao.NewGORMJobDAO(db)
	cronJobRepository := repository.NewPreemptCronJobRepository(jobDAO)
	cronJobService := service.NewCronJobService(cronJobRepository, loggerV1)
	cronJobServiceServer := grpc.NewCronJobServiceServer(cronJobService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxServer(cronJobServiceServer, client, loggerV1)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewGORMJobDAO, repository.NewPreemptCronJobRepository, service.NewCronJobService)

var thirdProvider = wire.NewSet(ioc.InitDB, ioc.InitEtcdClient, ioc.InitLogger)
