// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rwpp/RzWeLook/ranking/grpc"
	"github.com/rwpp/RzWeLook/ranking/ioc"
	"github.com/rwpp/RzWeLook/ranking/repository"
	"github.com/rwpp/RzWeLook/ranking/repository/cache"
	"github.com/rwpp/RzWeLook/ranking/service"
)

// Injectors from wire.go:

func Init() *App {
	loggerV1 := ioc.InitLogger()
	client := ioc.InitEtcdClient()
	interactiveServiceClient := ioc.InitInterActiveRpcClient()
	articleServiceClient := ioc.InitArticleRpcClient()
	cmdable := ioc.InitRedis()
	rankingCache := cache.NewRankingCache(cmdable)
	rankingLocalCache := cache.NewRankingLocalCache()
	rankingRepository := repository.NewRankingRepository(rankingCache, rankingLocalCache)
	rankingService := service.NewBatchRankingService(interactiveServiceClient, articleServiceClient, rankingRepository)
	rankingServiceServer := grpc.NewRankingServiceServer(rankingService)
	server := ioc.InitGRPCxServer(loggerV1, client, rankingServiceServer)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(cache.NewRankingLocalCache, cache.NewRankingCache, repository.NewRankingRepository, service.NewBatchRankingService)

var thirdProvider = wire.NewSet(ioc.InitRedis, ioc.InitInterActiveRpcClient, ioc.InitArticleRpcClient, ioc.InitEtcdClient, ioc.InitLogger)
