db:
  src:
    dsn: "root:root@tcp(localhost:13316)/welook"
  dst:
    dsn: "root:root@tcp(localhost:13316)/welook_intr"

migrator:
  pattern: "src_only"
  web:
    addr: ":8082"
redis:
  addr: "localhost:6379"

kafka:
  addrs:
    - "localhost:9094"

grpc:
  server:
    port: "8090"
    etcdAddrs:
      - "localhost:12379"

