db:
  dsn: "root:root@tcp(localhost:13316)/welook"

redis:
  addr: "localhost:6379"

kafka:
  addrs:
    - "localhost:9094"
etcd:
  endpoints:
    - "localhost:12379"

grpc:
  #  使用 etcd 来作为服务发现
  #  配置客户端的时候一定要小心端口，要填对
  #  当然对应的服务也要启动起来
  client:
    user:
      target: "etcd:///service/user"
    article:
      target: "etcd:///service/article"
    code:
      target: "etcd:///service/code"
    intr:
      target: "etcd:///service/interactive"
    reward:
      target: "etcd:///service/reward"
#流量控制的grpc配置
#grpc:
#  client:
#    intr:
#      addr: "localhost:8090"
#      #name: "interactive"
#      secure: false
#      #etcdAddr: "localhost:12379"
##      全部都走grpc调用
#      threshold: 100

test: "hello,babc"