// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rwpp/RzWeLook/user/grpc"
	"github.com/rwpp/RzWeLook/user/ioc"
	"github.com/rwpp/RzWeLook/user/repository"
	"github.com/rwpp/RzWeLook/user/repository/cache"
	"github.com/rwpp/RzWeLook/user/repository/dao"
	"github.com/rwpp/RzWeLook/user/service"
	"github.com/rwpp/RzWeLook/wego"
)

// Injectors from wire.go:

func Init() *wego.App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	userDAO := dao.NewUserDAO(db)
	cmdable := ioc.InitRedis()
	userCacheInterface := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCacheInterface)
	userService := service.NewUserService(userRepository)
	userServiceServer := grpc.NewUserServiceServer(userService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxServer(userServiceServer, client, loggerV1)
	app := &wego.App{
		GRPCServer: server,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitLogger, ioc.InitDB, ioc.InitRedis, ioc.InitEtcdClient)
